/**
 * This program takes real time data generated by trident devices 
 * and maps it to an unencrypted json string 
 * Author: Trident Holder
 * Date: 05 Jan, 2020
 * 
 */
#include <ArduinoJson.h>

// Standard unencrypted real time sensor data 
long  latitude = 19.12038;
long longitude = 76.82321;
int temperature = 22;
int gas = 2;
bool sos = 0;

void setup() {
  // put your setup code here, to run once:
Serial.begin(9600);
}

void loop() {

// call Method for json conversion logic
 convertDataToJson();
 delay(5000);
}


void convertDataToJson(){
  // Allocate the JSON document
  //
  // Inside the brackets, 200 is the RAM allocated to this document.
  // Don't forget to change this value to match your requirement.
  // Use arduinojson.org/v6/assistant to compute the capacity.
  StaticJsonDocument<200> doc;
   // put your main code here, to run repeatedly:
doc["lat"] = latitude;
doc["long"] = longitude;
doc["temp"] = temperature;
doc["gas"] = gas;
doc["sos"] = sos;


serializeJson(doc, Serial);
// The above line prints:
// {"sensor":"gps","time":1351824120,"data":[48.756080,2.302038]}

// Start a new line
Serial.println();

// Generate the prettified JSON and send it to the Serial port.
//
serializeJsonPretty(doc, Serial);
  // The above line prints:
  // {
  //   "sensor": "gps",
  //   "time": 1351824120,
  //   "data": [
  //     48.756080,
  //     2.302038
  //   ]
  // }

Serial.println();
  }
